### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by sgquin** [sgquin/mealMaker#1]
hi zak
thank you for agreeing to help me with this. 
when i run the code, it says line 48 is where the issue is, but I'm thinking that that's not where it is. 

it says cannot access '.price' of undefined, but i don't know why it's undefined. 

i think that my addDishToCourse() method isn't working, and therefore 'appetizer' ends up being an empty array, instead of an array of objects filled with 'dish',

but i don't see why it's not working...

**Comment by zaksoup** [comment]
please paste full text of the errors you're seeing and steps to reproduce

**Comment by sgquin** [comment]
≈> node mealMaker.js
/Users/sharkbyte/Documents/CodeCamp/codecademyProjects/mealMaker/mealMaker.js:47
      const totalPrice = appetizer.price + main.price + dessert.price;
                                                                ^

TypeError: Cannot read property 'price' of undefined
    at Object.generateRandomMeal (/Users/sharkbyte/Documents/CodeCamp/codecademyProjects/mealMaker/mealMaker.js:47:65)
    at Object.<anonymous> (/Users/sharkbyte/Documents/CodeCamp/codecademyProjects/mealMaker/mealMaker.js:66:6)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)


issue #1

**Comment by zaksoup** [comment]
The error is correct. It's telling you that `dessert` is currently `undefined`. Try adding a `console.log(dessert)` on line 46 and see what the output is. Probably not what you expect. Why could that be? What's happening when you call `this.getRandomDishFromCourse('desserts');`? Are there any desserts on the menu to be returned from that method? What does `getRandomDishFromCourse(string)` return if a dish for a given type hasn't been added previously with `addDishToCourse()`

**Comment by sgquin** [comment]
thanks. resolved
